services:
  incinera-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: incinera-web
    restart: always
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - incinera-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

networks:
  incinera-network:
    external: true
