name: CD Deploy to VM

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Landing Page to CIn VM
    runs-on: self-hosted

    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy
        run: |
          PROJECT_DIR="$HOME/INCINERA"

          if [ ! -d "$PROJECT_DIR" ]; then
            git clone https://github.com/Atletica-Incinera/INCINERA.git "$PROJECT_DIR"
          fi

          cd "$PROJECT_DIR"
          git fetch --all
          git reset --hard origin/main

          # Garante que a rede existe
          docker network inspect incinera-network >/dev/null 2>&1 || docker network create incinera-network

          echo '${{ secrets.DOTENV_FILE }}' > .env

          docker compose up -d --build --remove-orphans
          docker image prune -f

          echo "Deploy da Landing Page finalizado com sucesso!"
